services:
  postgres:
    image: postgres:15
    container_name: imbuo_library_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: imbuo_library
      POSTGRES_USER: imbuo
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
